// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATKs7dArLtzT_VblKcZAhz-dkVRMvtZGI',
    appId: '1:602186457091:web:52b1330cff9ad5d090ae36',
    messagingSenderId: '602186457091',
    projectId: 'bimantara-3828c',
    authDomain: 'bimantara-3828c.firebaseapp.com',
    storageBucket: 'bimantara-3828c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDm6tNNY0sG71CF8yosMrMkNztq-UMJIM',
    appId: '1:602186457091:android:31c22518afbcc1d490ae36',
    messagingSenderId: '602186457091',
    projectId: 'bimantara-3828c',
    storageBucket: 'bimantara-3828c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkICTYVtaE6IH6Ow0zNUriS-NQJfhiNOo',
    appId: '1:602186457091:ios:a1aaefac5cde411b90ae36',
    messagingSenderId: '602186457091',
    projectId: 'bimantara-3828c',
    storageBucket: 'bimantara-3828c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkICTYVtaE6IH6Ow0zNUriS-NQJfhiNOo',
    appId: '1:602186457091:ios:ce76b3beef0e5b0690ae36',
    messagingSenderId: '602186457091',
    projectId: 'bimantara-3828c',
    storageBucket: 'bimantara-3828c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
